### ISSUE TITLE
Bug in Laboratory 2 Assignment for Computer Science 100

### ISSUE THREAD

**Issue by reid7danny** [Allegheny-Computer-Science-100-F2019/cs100-F2019-lab2-starter#1]
In the reflection section of the Lab 2 assignment, for the portion that asks the user to add an explanation to each Java code statement, the code statement `import java.util.Date` is displayed twice. One of the statements should say `import java.util.Scanner`. @gkapfham

**Comment by gkapfham** [comment]
Hello @reid7danny thanks for raising this issue. I fixed the problem so that one of them refers to `java.util.Date` and the other refers to `java.util.Scanner`. I wanted students to start to think about the `Scanner` because we will use it in upcoming programming projects and assignments. However, I accidentally pasted in the wrong line from the code. Thanks for pointing out this mistake.

Since I think that this issue is resolved, I am going to close it. If you think that there are still please outstanding issues, you can re-open this issue or raise a new one.
