### ISSUE TITLE
Yards per Mile VS. Miles per Yards

### ISSUE THREAD

**Issue by whitek2** [Allegheny-Computer-Science-100-F2019/cs100-F2019-lab2-starter#2]
The declared variable is the number of yards in a mile (1760); the third line of output is asking for the number of miles in a yard (.0005681818). Since these are two different meanings, it can be confusing as to how to get the "proper" output.

**Comment by gkapfham** [comment]
Hi @whitek2 thanks for raising this issue!

I fixed this the problem with the label so that it better matches the name of the variable.

I also fixed the spelling mistake in one of the comments of the referenced source code.

I am closing this issue as I anticipate that it is correctly resolved. If there is any further work that you think I need to do to resolve this issue, please let me know. Thanks again!
